supertokens/supertokens-golang

- .circleci/setupAndTestWithFrontend.sh
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- coreDriverInterfaceSupported.json
- recipe/session/recipeImplementation.go
- recipe/session/sessionFunctions.go
- recipe/session/sessmodels/models.go
- recipe/session/utils.go
- supertokens/constants.go
Uses an array of signing keys for verification
-   https://github.com/supertokens/supertokens-core/issues/305
-   If no such branch exists, then create one from the latest released …
> makes changes as per new CDI - smooth signing key rotation

- CHANGELOG.md
- frontendDriverInterfaceSupported.json
- recipe/thirdparty/api/implementation.go
- recipe/thirdparty/api/signinup.go
- recipe/thirdparty/tpmodels/apiInterface.go
- recipe/thirdpartyemailpassword/api/implementation.go
- recipe/thirdpartyemailpassword/api/thirdPartyAPIImplementation.go
- recipe/thirdpartyemailpassword/tpepmodels/apiInterface.go
-   https://github.com/supertokens/frontend-driver-interface/issues/24
-   If no such branch exists, then create one …
> adds authCodeResponse support

- CHANGELOG.md
- examples/go.sum
- examples/with-chi-oso/main.go
- examples/with-chi/main.go
- examples/with-gin/config/config.go
- examples/with-http/main.go
- examples/with-labstack-echo/main.go
- examples/with-mux/main.go
- examples/with-twirp/cmd/server/main.go
- go.mod
- go.sum
- recipe/thirdparty/api/appleRedirect.go
- recipe/thirdparty/api/implementation.go
- recipe/thirdparty/main.go
- recipe/thirdparty/providers/apple.go
- recipe/thirdparty/providers/facebook.go
- recipe/thirdparty/providers/github.go
- recipe/thirdparty/providers/google.go
- recipe/thirdparty/recipe.go
- recipe/thirdparty/tpmodels/apiInterface.go
- recipe/thirdparty/tpmodels/models.go
- recipe/thirdparty/tpmodels/providers.go
- recipe/thirdpartyemailpassword/api/implementation.go
- recipe/thirdpartyemailpassword/api/thirdPartyAPIImplementation.go
- recipe/thirdpartyemailpassword/tpepmodels/apiInterface.go
- supertokens/main.go
- supertokens/normalisedURLPath_test.go
- supertokens/supertokens.go
Adds Apple sign in and new API as per FDI 1.10
-   https://github.com/supertokens/supertokens-core/issues/320
-   https://github.com/supertokens/supertokens-golang/issues/20
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) …
> starts working on adding apple sign in

- recipe/thirdparty/api/authorisationUrl.go
- recipe/thirdparty/api/signinup.go
- recipe/thirdparty/api/utils.go
- recipe/thirdparty/utils.go
Adds `IsDefault` bool to third party providers
-   https://github.com/supertokens/supertokens-core/issues/320
-   If no …
> Is default third party provider

- CHANGELOG.md
- recipe/session/middleware.go
- supertokens/constants.go
- supertokens/models.go
- supertokens/supertokens.go
- supertokens/utils.go
Does not send a response if the user has already sent a response
- https://github.com/supertokens/supertokens-node/issues/197
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released …
> Custom response

- CHANGELOG.md
- examples/with-chi/main.go
- recipe/emailpassword/api/signup.go
- recipe/emailpassword/api/utils.go
- recipe/emailpassword/errors/errors.go
- recipe/thirdparty/api/implementation.go
- recipe/thirdparty/api/signinup.go
- recipe/thirdparty/main.go
- recipe/thirdparty/providers/discord.go
- recipe/thirdparty/providers/googleWorkspaces.go
- recipe/thirdparty/tpmodels/apiInterface.go
- recipe/thirdparty/tpmodels/providers.go
- recipe/thirdparty/tpmodels/recipeInterface.go
- recipe/thirdpartyemailpassword/api/implementation.go
- recipe/thirdpartyemailpassword/api/thirdPartyAPIImplementation.go
- recipe/thirdpartyemailpassword/recipeimplementation/main.go
- recipe/thirdpartyemailpassword/recipeimplementation/thirdPartyRecipeImplementation.go
- recipe/thirdpartyemailpassword/tpepmodels/apiInterface.go
- recipe/thirdpartyemailpassword/tpepmodels/recipeInterface.go
- supertokens/constants.go
- Adds sign in with google workspaces and discord
- Changes struct type of form field error
- If getting profile info fails, we send that as a form field error to the frontend.
-   https://github.com/supertokens/supertokens-core/issues/320
-   To know which one it is, run find the latest released tag (`git tag`) in the …
> Thirdparty providers

- CHANGELOG.md
- recipe/thirdpartyemailpassword/recipeimplementation/main.go
Fixes issue https://github.com/supertokens/supertokens-node/issues/244
-   https://github.com/supertokens/supertokens-node/issues/244
None
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the …
> Throws an error in case user tries to update email / password of a third party user

- CHANGELOG.md
- recipe/session/sessionFunctions.go
Fixed typecasting in the following functions: 
- revokeAllSessionsForUserHelper
- getAllSessionHandlesForUserHelper 
- revokeMultipleSessionsHelper
-   none
-   In …
> Fix session functions

- CONTRIBUTING.md
Added the contributing guide
-   https://github.com/supertokens/supertokens-golang/issues/25
None
None
-   If no such …
> docs: added contributing guide

- recipe/thirdparty/override_test.go
- recipe/thirdparty/testingUtils.go
- fixed the reset all utility in thirdparty recipe 
none
none
none
-   If no such branch exists, then create one from …
> test: fixed the testing utility in thirdparty recipe 

- CONTRIBUTING.md
- test/unittesting/testingutils.go
- fixed the utility function that caused the issue while running the tests in circle-ci
none
none
none
-   If no such …
> test: fixed the testing utility that caused issues while running tests with circleCI

- CHANGELOG.md
- recipe/session/recipe.go
- recipe/session/recipeImplementation.go
- recipe/session/sessionFunctions.go
- supertokens/logger.go
- supertokens/supertokens.go
- supertokens/utils.go
- Adds debug messages
- Messages are based on the ones in supertokens-node
None
All existing tests pass
None
-   [ ] ~~Changelog has been updated~~
-   [ ] ~~Changes to the version if needed~~
-   ~~In `supertokens/constants.go > version variable`~~
-   [ ] ~~Issue this PR against the latest non released version branch.~~
-   ~~To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the …
> feat: Add debug logs

- .github/helpers/.gitignore
- .github/helpers/package.json
- .github/workflows/pre-commit-hook-run.yml
- .github/workflows/tests-pass-check-pr.yml
- .github/workflows/tests.yml
- CHANGELOG.md
Added Github Actions for Pre-commit hook and Running tests
-   If no such branch exists, then create one from the latest …
> chore: Added Github Actions for Pre-commit hook and Running tests

- ingredients/emaildelivery/edmodels/models.go
- ingredients/emaildelivery/main.go
- ingredients/emaildelivery/services/smtpmodels/models.go
Adds models for email delivery ingredient
> feat: adds ingredient type and impl for email delivery

- CHANGELOG.md
- recipe/passwordless/api_test.go
- recipe/passwordless/config_test.go
- recipe/passwordless/recipeFucntions_test.go
- test/unittesting/testingutils.go
Added configTests, apiResultTests and recipeFunctionTests to passwordless recipe 
- https://github.com/supertokens/supertokens-golang/issues/24
none
none
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is …
> feat(test): Added unit tests to passwordless recipe 

- test/frontendIntegration/main.go
Added `/update-jwt-with-handle` route to the testing server of the frontendIntegration tests 
none
none
none
-   If no …
> feat(fixing frontend integration test): added a route to update-access-token-payload

- recipe/passwordless/api/implementation.go
- recipe/passwordless/emaildelivery/backwardCompatibilityService/main.go
- recipe/passwordless/emaildelivery/smtpService/main.go
- recipe/passwordless/emaildelivery/smtpService/passwordlessLogin.go
- recipe/passwordless/emaildelivery/smtpService/serviceImplementation.go
- recipe/passwordless/passwordless_email_test.go
- recipe/passwordless/passwordlessfunctions.go
- recipe/passwordless/plessmodels/apiInterface.go
- recipe/passwordless/plessmodels/models.go
- recipe/passwordless/recipe.go
- recipe/passwordless/utils.go
- recipe/thirdpartypasswordless/recipe.go
- test/unittesting/testingutils.go
email delivery impl for passwordless
-   [ ] Had installed and ran …
> feat: emaildelivery impl for passwordless

- recipe/emailpassword/main.go
- recipe/emailverification/main.go
- recipe/passwordless/main.go
- recipe/thirdparty/main.go
- recipe/thirdpartyemailpassword/main.go
- recipe/thirdpartypasswordless/main.go
> fix: Expose SendEmail and SendSms functions

- recipe/passwordless/passwordlessfunctions.go
> fix: error from API response

- recipe/emailpassword/emaildelivery/smtpService/passwordReset.go
- recipe/emailpassword/emailpassword_email_test.go
- recipe/emailverification/emaildelivery/smtpService/emailVerify.go
- recipe/emailverification/emailverification_email_test.go
- recipe/passwordless/emaildelivery/smtpService/passwordlessLogin.go
- recipe/passwordless/passwordless_email_test.go
- recipe/passwordless/passwordless_sms_test.go
- recipe/passwordless/smsdelivery/twilioService/passwordlessLogin.go
> fix: Updated Email and SMS templates

- recipe/passwordless/passwordlessfunctions.go
> fix: Updated free SMS quota print message

- recipe/emailpassword/passwordResetFunctions.go
- recipe/emailverification/emailverificationfunctions.go
> chore: Remove todos

- recipe/passwordless/passwordlessfunctions.go
> fix: fixing passwordless API request body

- recipe/passwordless/emaildelivery/smtpService/passwordlessLogin.go
> fix: template fix for OTP

- CHANGELOG.md
- recipe/passwordless/api/consumeCode.go
- recipe/passwordless/api/createCode.go
- recipe/passwordless/api/doesEmailExist.go
- recipe/passwordless/api/doesPhoneNumberExist.go
- recipe/passwordless/api/implementation.go
- recipe/passwordless/config_test.go
- recipe/passwordless/plessmodels/apiInterface.go
- recipe/thirdpartypasswordless/config_test.go
- recipe/thirdpartypasswordless/tplmodels/apiInterface.go
- Changes to passwordless and thirdpartypasswordless recipe (passwordless part of it)
- Returns a regular error in case there is an issue sending SMS or email in passwordless recipe.
-  https://github.com/supertokens/supertokens-node/issues/220
> Api general error passwordless thirdpartypasswordless

- CHANGELOG.md
- recipe/jwt/api/getJWKS.go
- recipe/jwt/api/implementation.go
- recipe/jwt/jwtmodels/apiInterface.go
- recipe/jwt/override_test.go
- recipe/openid/api/getOpenIdDiscoveryConfiguration.go
- recipe/openid/api/implementation.go
- recipe/openid/openidmodels/apiInterface.go
- recipe/openid/override_test.go
- recipe/session/api/signout.go
- recipe/session/sessmodels/apiInterface.go
- Changes to session, jwt, openid recipe
- Changes `GetJWKSGET` in JWT recipe to return `GetJWKSAPIResponse` (that also contains a General Error response)
- Changes `GetOpenIdDiscoveryConfigurationGET` in Open ID recipe to return `GetOpenIdDiscoveryConfigurationAPIResponse` (that also contains a General Error response)
-  https://github.com/supertokens/supertokens-node/issues/220
> general error: changes to session, jwt, openid recipe

- recipe/passwordless/passwordless_email_test.go
- recipe/passwordless/passwordless_sms_test.go
- recipe/thirdpartypasswordless/tpl_email_test.go
- recipe/thirdpartypasswordless/tpl_sms_test.go
-   [ ] Issue this PR against the …
> fix: Unittest issue

- CHANGELOG.md
- recipe/session/config_test.go
- recipe/session/session_test.go
- recipe/session/utils.go
-  https://github.com/supertokens/supertokens-golang/issues/141
Added unit tests.
-   To know which one it is, run find the …
> fix: Fixes Cookie SameSite config validation

- CHANGELOG.md
- recipe/passwordless/passwordless_email_test.go
- recipe/passwordless/passwordless_sms_test.go
- recipe/thirdpartypasswordless/tpl_email_test.go
- recipe/thirdpartypasswordless/tpl_sms_test.go
- test/unittesting/testingutils.go
-   [ ] ~~Changes to the version if needed~~
-   ~~In `supertokens/constants.go > version variable`~~
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) …
> test: Passwordless login unit tests for resend

- CHANGELOG.md
- recipe/session/main.go
- recipe/session/recipeImplementation.go
- recipe/session/session.go
- recipe/session/sessionFunctions.go
- recipe/session/session_test.go
- recipe/session/sessionwithjwt/recipeImplementation.go
- recipe/session/sessmodels/recipeInterface.go
Similar to https://github.com/supertokens/supertokens-node/pull/340
-   https://github.com/supertokens/backend/issues/83
Updated tests to check for new behavior
-   [ ] Issue this PR against the latest non released version …
> fix: Session error throwing fix

- recipe/emailverification/emailverificationClaim.go
- recipe/session/claims/claims.go
- recipe/session/claims/primitiveArrayClaim.go
- recipe/session/claims/primitiveClaim.go
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is …
> fix: removed getLastRefetchTime from SessionClaim base class

- examples/with-labstack-echo/main.go
- recipe/emailpassword/emailExistsAndVerificationCheck_test.go
- recipe/emailverification/api/emailverify.go
- recipe/emailverification/api/generateEmailVerifyToken.go
- recipe/emailverification/api/implementation.go
- recipe/emailverification/evmodels/apiInterface.go
- recipe/session/api/implementation.go
- recipe/session/api/signout.go
- recipe/session/claimsWithJWT_test.go
- recipe/session/claimsutils_test.go
- recipe/session/createNewSession_test.go
- recipe/session/getClaimValue_test.go
- recipe/session/main.go
- recipe/session/recipeImplementation.go
- recipe/session/removeClaim_test.go
- recipe/session/session.go
- recipe/session/sessionwithjwt/recipeImplementation.go
- recipe/session/sessionwithjwt/sessionContainer.go
- recipe/session/sessmodels/apiInterface.go
- recipe/session/sessmodels/models.go
- recipe/session/sessmodels/recipeInterface.go
- recipe/session/setClaimValue_test.go
- recipe/session/utils.go
- recipe/session/validateClaimsForSessionHandle_test.go
- recipe/session/verifySession_test.go
- test/auth-react-server/main.go
- Changed SessionContainer -> TypeSessionContainer
- Created new type SessionContainer = *TypeSessionContainer
- Replaced all *SessionContainer to SessionContainer
- Updated JWT override of SessionContainer
-   [ ] Issue this PR against the …
> fix: Session container to pointer

- examples/with-chi-oso/main.go
- examples/with-chi/main.go
- examples/with-fiber/main.go
- examples/with-gin/config/config.go
- examples/with-go-zero/main.go
- examples/with-http/main.go
- examples/with-labstack-echo/main.go
- examples/with-mux/main.go
- examples/with-twirp/cmd/server/main.go
Tested with auth react, `session_grants` branch, `with-thirdpartyemaillpassword` example
- …
> fix: Session claims example changes

- recipe/userroles/claims_test.go
- Order of permissions might change randomly. adjusting test to work with that.
Unit test
-   To know which one it is, run find the latest released tag (`git tag`) in the …
> fix: Unit test fix

- recipe/session/middleware.go
- recipe/thirdparty/recipe.go
- recipe/thirdpartyemailpassword/recipe.go
- recipe/thirdpartypasswordless/recipe.go
- test/auth-react-server/main.go
- fixed issue with handleError in couple of recipes
- fixed default userContext for verifySession
- added newly required endpoints for auth-react-test server
Ran auth react tests locally
-   [ ] Issue this PR against the latest non released …
> fix: integration test updates & fixes

- .circleci/config.yml
Fixing git config for npm install
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git …
> fix: circleci git config

- recipe/session/recipeImplementation.go
> fix: Clear cookies integration test fix

- CHANGELOG.md
- recipe/thirdparty/api/utils.go
- recipe/thirdparty/findProvider_test.go
Fixed the issue and added tests
-   [x] Issue this PR against the …
> fix: fixed findRightProvider crash issue

- CHANGELOG.md
- recipe/thirdparty/provider_test.go
- recipe/thirdparty/providers/google.go
- recipe/thirdparty/providers/googleWorkspaces.go
- recipe/thirdpartypasswordless/provider_test.go
Updated google token endpoint
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git …
> fix: Updated google token endpoint

- examples/with-fiber/main.go
Handling the call of the next in the correct way.
Manually tested for session required, not required and default options.
-   To know which one it is, run find the latest …
> fix: fiber example

- .github/PULL_REQUEST_TEMPLATE.md
PR template
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose …
> fix: PR template changes for thirdparty

- CHANGELOG.md
- recipe/dashboard/api/usersGet.go
- supertokens/constants.go
-   [ ] Issue this PR against the …
> fix: panic in dashboard usersGet API

- CHANGELOG.md
Updated changelog based on changes done so far and also some of the recent changes discussed.
-   In …
> chore: thirdparty rework changelog

- recipe/thirdparty/api/implementation.go
- recipe/thirdparty/providers/config_utils.go
- recipe/thirdparty/providers/custom.go
- recipe/thirdparty/providers/discord.go
- recipe/thirdparty/tpmodels/models.go
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git …
> fix: requireEmail option

- recipe/multitenancy/api/implementation.go
- recipe/multitenancy/multitenancymodels/recipeInterface.go
- recipe/thirdparty/api/authorisationUrl.go
- recipe/thirdparty/recipe.go
Typos and few minor things.
-   [ ] Issue this PR against the …
> fix: fixes based on node SDK

- test/frontendIntegration/static/index.html
Updated index.html
-   [ ] Issue this PR against the latest non …
> fix: Website test issue

- .circleci/setupAndTestWithFrontend.sh
> fix: updated website test script

- CHANGELOG.md
- recipe/thirdparty/apple_callback_test.go
Added unit test for apple callback
-   [x] Issue this PR against …
> test: Apple callback test

- .circleci/config.yml
- .circleci/config_continue.yml
- .circleci/generateConfig.sh
> chore: Change circleci configs to add parallelism

- .circleci/config_continue.yml
> chore: Change circleci configs

- recipe/dashboard/api/implementation.go
- recipe/dashboard/api/utils.go
- supertokens/supertokens.go
- supertokens/userIdMapping.go
- supertokens/utils.go
> feat: Cdi check

- CHANGELOG.md
- recipe/emailpassword/api/generatePasswordResetToken.go
- recipe/emailpassword/api/passwordReset.go
- recipe/emailpassword/api/signin.go
- recipe/emailpassword/api/signup.go
- recipe/emailpassword/api/utils.go
- recipe/emailpassword/formFieldValidator_test.go
- supertokens/constants.go
Fixed validation related to form fields
-   https://github.com/supertokens/supertokens-golang/issues/254
Added test to verify all the APIs
-   To know which …
> fix: Input validation fix for emailpassword APIs

- examples/go.sum
- recipe/emailpassword/api/utils.go
- recipe/emailpassword/authFlow_test.go
- recipe/emailpassword/formFieldValidator_test.go
Fixed 500 errors and the test cases
-   [ ] Had installed and ran …
> fix: build fix

- CHANGELOG.md
- recipe/emailverification/emaildelivery/smtpService/emailVerify.go
- supertokens/constants.go
> fix: email template for verify email updated

- CHANGELOG.md
- recipe/dashboard/api/usersGet.go
- recipe/emailpassword/deleteUser_test.go
- recipe/emailpassword/userIdMapping_users_test.go
- recipe/emailpassword/user_test.go
- recipe/thirdparty/users_test.go
- recipe/thirdpartypasswordless/users_test.go
- supertokens/constants.go
- supertokens/main.go
Added missing arguments from getUsersNewestFirst and getUsersOldestFirst …
> feat: Function signature update

- recipe/session/recipeImplementation.go
- test/frontendIntegration/main.go
- Updates frontend integration server
-  
Existing integration tests pass
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, …
> Update integration server and fix for tests

- recipe/session/session_test.go
- Add test for get session when request does not contain session, check database is true and session required is false
-   
NA
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest …
> Adds tests for GetSession

- CHANGELOG.md
- recipe/emailverification/api/implementation.go
- recipe/session/accessToken.go
- recipe/session/recipeImplementation.go
- recipe/session/session.go
- recipe/session/sessionFunctions.go
- recipe/session/sessionRequestFunctions.go
- supertokens/constants.go
- Adds debug logs whenever the SDK returns try refresh token or unauthorized errors to make debugging easier
- 
NA
- …
> chore: Add additional debug logs for session functions

- recipe/session/testingUtils.go
> Clean up jwks background tasks between tests

- test/frontendIntegration/main.go
> Fix integration tests

- recipe/dashboard/constants/constants.go
- recipe/dashboard/recipe.go
- recipe/dashboard/utils.go
- recipe/emailpassword/authFlow_test.go
- recipe/emailpassword/recipe.go
- recipe/emailverification/recipe.go
- recipe/jwt/recipe.go
- recipe/multitenancy/multitenancymodels/models.go
- recipe/multitenancy/recipe.go
- recipe/openid/recipe.go
- recipe/passwordless/recipe.go
- recipe/session/recipe.go
- recipe/thirdparty/recipe.go
- recipe/thirdpartyemailpassword/recipe.go
- recipe/thirdpartypasswordless/recipe.go
- recipe/usermetadata/recipe.go
- recipe/userroles/recipe.go
- supertokens/constants.go
- supertokens/recipeModule.go
- supertokens/supertokens.go
- test/unittesting/testingutils.go
https://github.com/supertokens/supertokens-node/pull/592
-   In `supertokens/constants.go > version …
> fix: router to handle tenantid

- recipe/userroles/claims.go
- recipe/userroles/claims_test.go
- recipe/userroles/deleteRole_test.go
- recipe/userroles/main.go
- recipe/userroles/recipeimplementation.go
- recipe/userroles/userroles_test.go
- recipe/userroles/userrolesmodels/recipeInterface.go
- test/auth-react-server/main.go
https://github.com/supertokens/supertokens-node/pull/600
-   In `supertokens/constants.go > version …
> fix: userroles impl

- CHANGELOG.md
- recipe/session/recipeImplementation.go
- recipe/session/session.go
- recipe/session/session_test.go
- supertokens/constants.go
-   https://github.com/supertokens/supertokens-golang/issues/298 …
> fix: session fix

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- recipe/dashboard/api/userdetails/userPasswordPut.go
- recipe/dashboard/api/userdetails/userPut.go
- recipe/dashboard/testingUtils.go
- recipe/dashboard/userPasswordPut_test.go
- recipe/dashboard/userPut_test.go
- recipe/session/accessTokenVersions_test.go
- recipe/session/recipeImplementation.go
- recipe/session/session.go
- recipe/session/session_test.go
- recipe/thirdpartyemailpassword/recipe.go
> fix: merge latest

- recipe/thirdparty/providers/activeDirectory.go
- recipe/thirdparty/providers/custom.go
- recipe/thirdparty/providers/facebook.go
- recipe/thirdparty/providers/google.go
- recipe/thirdparty/providers/okta.go
- https://github.com/supertokens/supertokens-node/pull/651
-   In `supertokens/constants.go > version …
> fix: provider fixes

- recipe/emailpassword/multitenancy_test.go
- recipe/multitenancy/main.go
- recipe/multitenancy/recipeimplementation.go
- recipe/multitenancy/tenants_crud_test.go
- recipe/passwordless/multitenancy_test.go
- recipe/passwordless/recipeimplementation.go
- recipe/thirdparty/multitenancy_test.go
- recipe/thirdparty/recipe.go
- recipe/thirdparty/tpmodels/models.go
- recipe/thirdparty/utils.go
- recipe/userroles/multitenancy_test.go
- test/unittesting/testingutils.go
- https://github.com/supertokens/supertokens-golang/pull/207
-   [ ] Had installed …
> fix: tests and fixes

- recipe/dashboard/api/analyticsPOST.go
- recipe/dashboard/api/usersCountGet.go
- recipe/emailpassword/user_test.go
- recipe/thirdparty/provider_config_test.go
- recipe/thirdparty/users_test.go
- recipe/userroles/testingUtils.go
- supertokens/main.go
- supertokens/supertokens.go
checklist and misc changes
-   [ ] Had installed and …
> fix: checklist and misc changes

- recipe/multitenancy/api/loginMethods.go
- recipe/multitenancy/multitenancymodels/models.go
- recipe/multitenancy/recipe.go
- recipe/session/sessionFunctions.go
- test/auth-react-server/main.go
> fix: for cicd

- CHANGELOG.md
- test/frontendIntegration/main.go
> fix: changelog and website test fixes

- recipe/thirdparty/providers/okta.go
> fix: okta domain

- CHANGELOG.md
- recipe/thirdparty/api/appleRedirect.go
- recipe/thirdparty/api/implementation.go
- supertokens/constants.go
> fix: apple redirect

- recipe/session/querier_test.go
> chore: Fix querier tests

- recipe/session/sessionwithjwt/recipeImplementation.go
- recipe/session/sessionwithjwt/sessionContainer.go
> fix: Fix jwt expiry check logic

- .circleci/authReact.sh
- .circleci/setupAndTestWithAuthReact.sh
> chore: Cicd changes

- .circleci/config_continue.yml
- test/auth-react-server/main.go
> fix: Update CICD config and auth react test server

- .circleci/setupAndTestWithAuthReact.sh
> fix: Fix cicd again

- .circleci/setupAndTestWithAuthReact.sh
- test/frontendIntegration/main.go
> fix: Fix cicd

- CHANGELOG.md
Updates changelog to mention the frontend SDK versions compatible with the multitenancy changes
-   In …
> chore: Update CHANGELOG for multitenancy

- .circleci/setupAndTestWithAuthReact.sh
> fix: Update CICD

- CHANGELOG.md
- recipe/dashboard/apiKeyProtector.go
- recipe/dashboard/dashboardmodels/models.go
- recipe/dashboard/errors/errors.go
- recipe/dashboard/recipeimplementation.go
- recipe/dashboard/utils.go
- supertokens/constants.go
> feat: Allow users to set emails as admins for user dashboard

- CHANGELOG.md
- recipe/emailpassword/authFlow_test.go
- recipe/emailpassword/epmodels/models.go
- recipe/passwordless/plessmodels/models.go
- recipe/thirdpartypasswordless/api_test.go
- supertokens/constants.go
-   https://github.com/supertokens/supertokens-golang/issues/377
-   [ ] Had …
> fix: timeJoined

- test/auth-react-server/main.go
> chore: Add email delivery config to third party email password config to fix tests

- recipe/thirdparty/provider_test.go
> chore: Fix third party provider tests

- recipe/thirdparty/providers/github.go
- recipe/thirdparty/providers/oauth2_impl.go
- recipe/thirdparty/providers/twitter.go
- recipe/thirdparty/providers/utils.go
> refactor: Check for status in github validate access token

- CHANGELOG.md
- recipe/dashboard/api/utils.go
- recipe/dashboard/userGet_test.go
- recipe/thirdpartypasswordless/signinupFeature_test.go
- recipe/thirdpartypasswordless/signoutFeature_test.go
- recipe/thirdpartypasswordless/testingUtils.go
- supertokens/constants.go
Added tests
NA
-   [ ] add an icon on the user management dashboard.
-   To know …
> fix: Fix issue of dashboard showing no user found for thirdparty users with thirdpartypasswordless

- CHANGELOG.md
- recipe/thirdparty/providers/linkedin.go
- supertokens/constants.go
This PR updates the LinkedIn OAuth implementation as per the [recent changes](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext#authenticating-members).
Tested manually
-   [ ] update switch statement in `recipe/thirdparty/providers/config_utils.go` file, …
> fix: LinkedIn OAuth

- CHANGELOG.md
- recipe/session/sessionFunctions.go
- recipe/thirdparty/providers/custom.go
- supertokens/constants.go
> fix: session functions

- test/frontendIntegration/main.go
> fix: cicd website test

- recipe/emailpassword/authMode_test.go
> test: fix test typos&errors
