recipe/emailverification/api/emailverify.go
recipe/emailverification/api/generateEmailVerifyToken.go
recipe/emailverification/api/implementation.go
recipe/emailverification/emailverificationfunctions.go
recipe/emailverification/recipe.go
recipe/emailverification/recipeimplementation.go
recipe/emailverification/schema/schema.go
recipe/emailverification/utils.go
supertokens/querier.go
supertokens/recipeModule.go
supertokens/schema.go
supertokens/supertokens.go

@Piyushhbhutoria I have made several changes:
- Removed use of `interface` and replaced them with `struct`
- Added proper error handling for all functions
- Fixed a bunch of "known" bugs (from my previous code review)
- Remove storing of `instance` inside structs to simulate singleton behavior
- Made APIKey a pointer to a string in querier
- Some functions that were supposed to be static were actually instance functions, fixed that
- Fixed normalization of emailverification recipe
- Used fixed returns types for recipe and API functions (as opposed to generic map interface)
- Added `otherHandler` var to APIOption (not sure if this is the right thing to do, but it's what's done in node)
- Using `MakeStruct` function pattern to create new structs.
- Removed unnecessary use of pointers in …

refactors all code except for session recipe

---

CHANGELOG.md
frontendDriverInterfaceSupported.json
recipe/emailpassword/recipe.go
recipe/emailverification/main.go
recipe/emailverification/recipe.go
recipe/jwt/api/getJWKS.go
recipe/jwt/api/implementation.go
recipe/jwt/constants.go
recipe/jwt/jwtmodels/apiInterface.go
recipe/jwt/jwtmodels/models.go
recipe/jwt/jwtmodels/recipeInterface.go
recipe/jwt/main.go
recipe/jwt/recipe.go
recipe/jwt/recipeimplementation.go
recipe/jwt/utils.go
recipe/thirdparty/recipe.go
recipe/thirdpartyemailpassword/recipe.go
supertokens/constants.go
supertokens/utils.go

Adds the JWT recipe
-   https://github.com/supertokens/for-zenhub/issues/16
Frontend integration and manual testing
-   If no such branch exists, then create one from the latest released branch.

Jwt recipe

---

CHANGELOG.md
supertokens/constants.go
supertokens/supertokens.go

Ignores routing based on rid if the value of it is `"anti-csrf"`
-  https://github.com/supertokens/supertokens-node/issues/202
No change required
-   Along with the associated array in `lib/ts/version.ts`
-   To know which one it is, run find the latest released tag …

ignores routing as per rid if the value is anti-csrf

---

CHANGELOG.md
go.mod
go.sum
recipe/thirdparty/providers/apple.go
recipe/thirdparty/providers/googleWorkspaces.go
supertokens/constants.go

I've release `v1.0.0` for `github.com/MicahParks/keyfunc` and intend on avoiding `/v2` and beyond. This PR upgrades the dependency to the newly release stable version.
None for this project.
I ran the existing tests in this repository, but did not contribute tests to this project. 
None should be required.
-   To know …

Update keyfunc to stable release

---

examples/with-labstack-echo/main.go

Fix error handling propagation
When testing with my routes, the supertokens Middleware would always return 200, when my route returned 400. Looking through the Echo docs, this is the proper block to use:
```go
if err := hf(c); err != nil {
c.Error(err)
}
```

Fix Error Propagation for echo.labstack

---

CHANGELOG.md
recipe/passwordless/deleteUser_test.go
recipe/passwordless/main.go
recipe/passwordless/plessmodels/recipeInterface.go
recipe/passwordless/recipe.go
recipe/passwordless/recipeimplementation.go
recipe/passwordless/testingUtils.go
recipe/thirdpartypasswordless/deleteUser_test.go
recipe/thirdpartypasswordless/main.go
recipe/thirdpartypasswordless/recipeimplementation/main.go
recipe/thirdpartypasswordless/recipeimplementation/passwordlessRecipeImplementation.go
recipe/thirdpartypasswordless/testingUtils.go
recipe/thirdpartypasswordless/tplmodels/recipeInterface.go

Adds delete email and phone number for passwordless and thirdpartypasswordless recipes
-  https://github.com/supertokens/supertokens-python/issues/107
TODO
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is …

feat: adds missing functions to passwordless recipe

---

CHANGELOG.md
recipe/passwordless/recipeFucntions_test.go
recipe/passwordless/recipeimplementation.go
supertokens/constants.go
test/unittesting/testingutils.go

Changed the request url to the core of revokeCode funtion in the recipeImplementation of the passwordless recipe 
none
none
none
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest …

fix: fixes bug in revokeCode function in the recipeImplementation of passwordless recipe

---

.github/workflows/enforce-go-mod-tidy.yml
CHANGELOG.md

Fixed existing go mod tidy workflow to also work in the examples folder
none
none
none
-   If no such branch exists, …

feat(go mod tidy workflow): Add github action to enforce go mod tidy in the examples folder

---

CHANGELOG.md
test/unittesting/testingutils.go

Fixed the stopSt function exposed by testing utils fixing breaking tests after core version 3.9
none
none
none
-   If no …

feat(fixing testingutils): Fixed testing utility function StopST 

---

ingredients/emaildelivery/main.go
recipe/emailverification/emailverification_email_test.go

Golang mail package does not allow `Name <email>` kind of formatting for the from header. We just need to pass the email id directly.
-   In `supertokens/constants.go > …

fix: Secure SMTP implementation

---

CHANGELOG.md
recipe/thirdparty/api/authorisationUrl.go
recipe/thirdparty/api/signinup.go
recipe/thirdparty/authorisationUrlFeature_test.go
recipe/thirdparty/signinupFeature_test.go
recipe/thirdpartyemailpassword/authorisationUrlFeature_test.go

fixed a typo in authorizationUrl api func when providers is nil
none
none
none
-   If no such branch exists, then create …

feat(fixing typo in thirdparty recipe): fixed a typo in authorizationUrl api func when providers is nil

---

CHANGELOG.md
recipe/passwordless/recipeFucntions_test.go
recipe/passwordless/recipeimplementation.go
supertokens/constants.go

Fixes sending `preAuthSessionID` instead of `preAuthSessionId` to the core
-  https://github.com/supertokens/supertokens-golang/issues/102
-   Added test to generate codes and list them using pre auth session ID
None
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then …

fix: issue https://github.com/supertokens/supertokens-golang/issues/102

---

CHANGELOG.md
recipe/emailpassword/updateEmailPass_test.go
supertokens/constants.go
supertokens/doneWriter.go

Check and wrap HttpWriter with DoneWriter only if it is not already wrapped.
Added Unit test
-   To know which one it is, run find the latest released tag …

fix: fixed custom response writing in API overrides

---

CHANGELOG.md
recipe/thirdpartypasswordless/main.go
supertokens/constants.go

Fixes the function signature of the `GetUserByThirdPartyInfo` function in the `thirdpartypasswordless` recipe.
none
none
none
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released …

feat: Fixes the function signature of the GetUserByThirdPartyInfo function in the thirdpartypasswordless recipe.

---

CHANGELOG.md
recipe/emailpassword/updateEmailPass_test.go
supertokens/constants.go
supertokens/supertokens.go

With custom response, default on general error is outputting extra chars, which should not be done. Have checked for done writer in all the places OnGeneralError is being called. That way, even user overridden OnGeneralError handler won't be called on custom response.
Have added unit test and also verified the unit test fails without the fix.
- …

fix: Fixes issue in writing custom response in API override with general error

---

CHANGELOG.md
recipe/emailpassword/api/generatePasswordResetToken.go
recipe/emailpassword/api/passwordReset.go
recipe/emailpassword/api/signin.go
recipe/emailpassword/api/signup.go
recipe/emailpassword/updateEmailPass_test.go
recipe/emailverification/api/emailverify.go
recipe/passwordless/api/consumeCode.go
recipe/passwordless/api/createCode.go
recipe/passwordless/api/resendCode.go
recipe/thirdparty/api/signinup.go
supertokens/constants.go
supertokens/utils.go

-   https://github.com/supertokens/supertokens-golang/issues/116
Added Unit test
-   To know which one it is, run find the latest released tag (`git tag`) in …

fix: copying body from request to be able to read again from API override

---

CHANGELOG.md
recipe/thirdparty/providers/facebook.go
supertokens/constants.go

- Query params were being passed as headers, which was incorrect.
- Added checks for reading members from generic map.
-   https://github.com/supertokens/supertokens-golang/issues/122
Tested manually with thirdparty recipe and react frontend …

fix: fixed facebook login

---

CHANGELOG.md
recipe/thirdparty/api/authorisationUrl.go
recipe/thirdparty/api/implementation.go
recipe/thirdparty/api/signinup.go
recipe/thirdparty/tpmodels/apiInterface.go
recipe/thirdparty/tpmodels/recipeInterface.go
recipe/thirdpartyemailpassword/api/implementation.go
recipe/thirdpartyemailpassword/api/thirdPartyAPIImplementation.go
recipe/thirdpartyemailpassword/recipeimplementation/main.go
recipe/thirdpartyemailpassword/recipeimplementation/thirdPartyRecipeImplementation.go
recipe/thirdpartyemailpassword/tpepmodels/apiInterface.go
recipe/thirdpartyemailpassword/tpepmodels/recipeInterface.go
recipe/thirdpartypasswordless/api/implementation.go
recipe/thirdpartypasswordless/api/thirdPartyAPIImplementation.go
recipe/thirdpartypasswordless/recipeimplementation/main.go
recipe/thirdpartypasswordless/recipeimplementation/thirdPartyRecipeImplementation.go
recipe/thirdpartypasswordless/signinupFeature_test.go
recipe/thirdpartypasswordless/tplmodels/apiInterface.go
recipe/thirdpartypasswordless/tplmodels/recipeInterface.go

- Throws general error from all thirdparty APIs except for apple redirect (that's intentional)
- `SignInUp` recipe function doesn't return `FIELD_ERROR` anymore in thirdparty, thirdpartypasswordless and thirdpartyemailpassword recipe.
- `SignInUpPOST` api function returns `GENERAL_ERROR` instead of `FIELD_ERROR` in thirdparty, thirdpartypasswordless and thirdpartyemailpassword recipe.
-   https://github.com/supertokens/supertokens-node/issues/220

changes to thirdparty related recipe

---

CHANGELOG.md
recipe/thirdparty/providers/google.go
recipe/thirdparty/providers/utils.go
supertokens/constants.go

Returning error when the status from APIs like https://graph.facebook.com/me returns a non 2xx status response.
-   https://github.com/supertokens/supertokens-golang/issues/139
Have tested manually by sending verified code and invalid code. …

fix: Fixes panic when call to thirdparty provider API returns a non 2xx status.

---

CHANGELOG.md
recipe/thirdpartypasswordless/recipe.go

Changes `getEmailForUserIdForEmailVerification` in thirdpartypasswordless to take into account passwordless user email as well in case the dev wants to customise the thirdpartypasswordless recipe's email verification functions to take into account passwordless users as well.
-   https://discord.com/channels/603466164219281420/987701400433725440/988016274443489300

fix: thirdpartypasswordless email verification fix

---

CHANGELOG.md
recipe/emailpassword/api/emailExists.go
recipe/emailpassword/api/generatePasswordResetToken.go
recipe/emailpassword/api/passwordReset.go
recipe/emailpassword/api/signin.go
recipe/emailpassword/api/signup.go
recipe/emailpassword/updateEmailPass_test.go
recipe/emailverification/api/emailverify.go
recipe/emailverification/api/generateEmailVerifyToken.go
recipe/jwt/api/getJWKS.go
recipe/openid/api/getOpenIdDiscoveryConfiguration.go
recipe/passwordless/api/consumeCode.go
recipe/passwordless/api/createCode.go
recipe/passwordless/api/doesEmailExist.go
recipe/passwordless/api/doesPhoneNumberExist.go
recipe/passwordless/api/resendCode.go
recipe/session/api/signout.go
recipe/thirdparty/api/authorisationUrl.go
recipe/thirdparty/api/signinup.go
supertokens/constants.go
supertokens/utils.go

Avoids panic when returning mal-formed API response after sending custom response in the API overrides. Checking for nil in the responses before using them.
-   https://github.com/supertokens/supertokens-golang/issues/107
-   [ ] ~~`frontendDriverInterfaceSupported.json` file has …

fix: fixed API responses panic issue

---

recipe/usermetadata/usermetadata_test.go

UTF-8 encoding was already part of the header in querier, added test for utf-8 data.
Also verified that the test fails on removing the header.
-   [ ] ~~Changelog has been updated~~
-   In …

test: added test for querier request with UTF-8 data

---

CHANGELOG.md
recipe/emailpassword/api/emailExists.go
recipe/emailpassword/api/generatePasswordResetToken.go
recipe/emailpassword/api/passwordReset.go
recipe/emailpassword/api/signin.go
recipe/emailpassword/api/signup.go
recipe/emailpassword/userContext_test.go
recipe/emailverification/api/emailverify.go
recipe/emailverification/api/generateEmailVerifyToken.go
recipe/jwt/api/getJWKS.go
recipe/openid/api/getOpenIdDiscoveryConfiguration.go
recipe/passwordless/api/consumeCode.go
recipe/passwordless/api/createCode.go
recipe/passwordless/api/doesEmailExist.go
recipe/passwordless/api/doesPhoneNumberExist.go
recipe/passwordless/api/resendCode.go
recipe/session/api/refresh.go
recipe/session/api/signout.go
recipe/thirdparty/api/appleRedirect.go
recipe/thirdparty/api/authorisationUrl.go
recipe/thirdparty/api/signinup.go
supertokens/utils.go

Adds the request (of type *http.Request) object from the API to the userContext object by default.
Added unit test
-   In `supertokens/constants.go > …

feat: Adds request object to default user context

---

CHANGELOG.md
recipe/session/session.go
recipe/session/session_test.go
test/unittesting/testingutils.go

When calling Session.revokeSession, we used to clear the cookies only if the session used to exist in the core. This was an incorrect thing to do cause at the time of API session verification, the session did exist, so we should always clear the cookie when this function is called.
-   https://github.com/supertokens/supertokens-node/issues/343
Added unit test.
-   [ ] …

fix: Signout clearing cookies issue

---

CHANGELOG.md
recipe/thirdparty/providers/apple.go
recipe/thirdparty/providers/googleWorkspaces.go
recipe/thirdparty/providers/utils.go

Passing refresh interval to the Keyfunc was causing background goroutine to keep the pointer and also ended up compounding refresh requests over time. Caching JWKS using url -> JWKS map and reusing the instance with each call.
-   https://github.com/supertokens/supertokens-golang/issues/155
Have manually tested that the Apple login works and also ensured the shared instance is getting used for subsequent calls.
-   [ ] …

fix: JWKS leaking goroutine issue

---

CHANGELOG.md
recipe/session/session_test.go

Ref - https://github.com/supertokens/supertokens-node/pull/367
This issue did not exist for golang, added test to verify the same.
Added test
-   To know which …

test: adds test for session container override

---

recipe/emailpassword/ep_userIdMapping_test.go
recipe/emailpassword/userIdMapping_create_test.go
recipe/emailpassword/userIdMapping_delete_test.go
recipe/emailpassword/userIdMapping_get_test.go
recipe/emailpassword/userIdMapping_updateInfo_test.go
recipe/emailpassword/userIdMapping_users_test.go
recipe/passwordless/pless_userIdMapping_test.go
recipe/thirdparty/tp_userIdMapping_test.go
recipe/thirdpartyemailpassword/tpep_userIdMapping_test.go
recipe/thirdpartypasswordless/tpl_userIdMapping_test.go

Fixed version check in tests
Manually tested with older version of core
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, …

fix: Userid mapping test fix for older version

---

recipe/emailpassword/emailExistsAndVerificationCheck_test.go
recipe/emailpassword/emailpassword_email_test.go
recipe/emailpassword/recipe.go
recipe/emailverification/api/implementation.go
recipe/emailverification/emailverificationClaim.go
recipe/emailverification/emailverification_email_test.go
recipe/emailverification/evclaims/claims.go
recipe/emailverification/recipe.go
recipe/session/claims/booleanClaim.go
recipe/session/claims/claims.go
recipe/session/claims/primitiveArrayClaim.go
recipe/session/claims/primitiveClaim.go
recipe/session/recipe.go
recipe/session/session.go
recipe/session/sessionwithjwt/sessionContainer.go
recipe/session/sessmodels/models.go

Have changed SessionClaim back to pointer. When creating derived instances, the function copies are being updated and when called from the base, new functions are not being called. The alternative solution would be to have function pointers for all of the functions and then update while de-referencing, but I find pointer to the base more clean and reliable.
Few adjustments in the tests to make it compatible with current changes.
Had forgotten to return the OK result in the loop inside `GetEmailForUserID`
Fixed PrimitiveArrayClaim to return pointer to sessionClaim, removed pointers for claim validators.
Fixed EV API implementation to use isVerified correctly.
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting …

fix: Session claims fixes

---

frontendDriverInterfaceSupported.json
recipe/session/claimsWithJWT_test.go

Fixed JWT test to run only for cdi >= 2.9
Removed 1.14 from fdi.
tested with 2.8 and 2.9
-   If no such branch exists, …

fix: Unit test fix

---

CHANGELOG.md
recipe/session/createNewSession_test.go

Updated unit test to check based on null being dropped from the core.
Added to changelog - dropped support for FDI 1.14
tested with new and old
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than …

fix: fixed unit test for null dropped in core

---

CHANGELOG.md
recipe/emailverification/emailverificationClaim.go
recipe/session/claims/primitiveArrayClaim.go
recipe/session/claims/primitiveClaim.go
recipe/session/createNewSession_test.go
recipe/session/fetchAndSetClaim_test.go

Using UnixNano instead of UnixMilli
-   [x] Issue this PR against …

fix: support go 1.16

---

CHANGELOG.md
recipe/emailverification/emailverificationClaim.go
recipe/session/claims/primitiveArrayClaim.go
recipe/session/claims/primitiveClaim.go
recipe/userroles/claims.go

fix: Remove default max age

---

CHANGELOG.md
examples/go.mod
examples/with-fiber/main.go

Fixes go fiber example to handle handler chaining correctly with verifySession.
- https://github.com/supertokens/supertokens-golang/issues/194
Tested that the example works as expected
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest …

fix: fiber example

---

CHANGELOG.md
recipe/session/claimsWithJWT_test.go

- Call MergeIntoAccessTokenPayload
- Verify that GetAccessTokenPayload["jwt"] contains the new value.
https://github.com/supertokens/supertokens-node/issues/423
-   To …

fix: added test for jwt mergeIntoAccessTokenPayload

---

recipe/session/claimsWithJWT_test.go

added version check for TestMergeIntoAccessTokenPayloadForJWT
-   [ …

fix: added version check for TestMergeIntoAccessTokenPayloadForJWT

---

recipe/session/session_refresh_test.go

Adds a few tests for different situations of revoking a session during refreshing
-   https://github.com/supertokens/supertokens-node/issues/418
-   In …

fix: session refresh tests

---

CHANGELOG.md
recipe/emailpassword/emaildelivery/backwardCompatibilityService/main.go
recipe/emailpassword/emailpassword_email_test.go
supertokens/constants.go

If the user is overriding the sendEmail function in emailpassword recipe to change the input email, their change will not get reflected since our implementation calls the getUserById function which will reset their changed email.
So we reassign the input email to the result of calling getUserById
-   Along …

fix: sendEmail override issue

---

CHANGELOG.md
recipe/dashboard/api/userdetails/userPasswordPut.go

Default password validator expects string input and does not work with pointer to string.
Manually tested change password in dashboard
-   To know which one it …

fix: fixes newPassword validation

---

CHANGELOG.md
ingredients/emaildelivery/main.go
ingredients/emaildelivery/smtpmodels.go

Adds optional username to SMTP settings which can be used if username is different from From.Email
- https://github.com/supertokens/supertokens-golang/issues/221
-   [x] Issue this PR against the latest non released version …

fix: Add username to SMTP settings

---

CHANGELOG.md
recipe/dashboard/api/userdetails/userGet.go
recipe/dashboard/api/utils.go
recipe/dashboard/dashboardmodels/models.go
recipe/emailpassword/config_test.go
recipe/emailpassword/main.go
recipe/emailpassword/recipe.go
recipe/passwordless/config_test.go
recipe/passwordless/main.go
recipe/passwordless/recipe.go
recipe/thirdparty/main.go
recipe/thirdparty/provider_test.go
recipe/thirdparty/recipe.go
recipe/thirdpartyemailpassword/config_test.go
recipe/thirdpartyemailpassword/main.go
recipe/thirdpartyemailpassword/recipe.go
recipe/thirdpartypasswordless/config_test.go
recipe/thirdpartypasswordless/main.go
recipe/thirdpartypasswordless/provider_test.go
recipe/thirdpartypasswordless/recipe.go
supertokens/constants.go

- Fixes an issue where fetching user details for a passwordless user with only a phone number present would send the wrong response payload to the frontend
- Updates dashboard version to 0.3
- Updates user GET API in dashboard recipe to handle if the recipe for the user being fetched was not initialised
-  
None
-   In …

fix: Update dashboard recipe user Get API

---

CONTRIBUTING.md

Refer to startTestEnv instead of startTestingEnv in contrib, according to https://github.com/supertokens/supertokens-root/commit/4baff668172055c74885f6f44359e6e3e8f0a78d
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if …

fix: Refer to startTestEnv instead of startTestingEnv in contrib

---

recipe/emailpassword/api/implementation.go

Use the same loop to extract both email and password from formFields.
https://github.com/supertokens/supertokens-golang/issues/220
Running locally, according to https://github.com/supertokens/supertokens-golang/blob/master/CONTRIBUTING.md#testing  …

fix: Merge emailpassword formFields loops

---

CHANGELOG.md
examples/with-fiber/main.go

What was wrong in the previous solution we settled for is calling the c.Next() outside of the adaptor. The problem with that is that the session container is till working with http Request and and Response objects that were created inside the adaptor, but now no longer in use. I think the right thing to call the next from within the adaptor itself. We still address the previous issue by returning the error that was returned by the c.Next() outside the adaptor.
Have verified user specified scenario. Also verified that the headers from user defined route and the SDK and the ones written directly to the net/http ResponseWriter are all reflecting in the resulting response correctly.
(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist …

fix: go fiber example fix

---

CHANGELOG.md
examples/with-chi-oso/main.go
examples/with-chi/main.go
examples/with-fiber/main.go
examples/with-gin/config/config.go
examples/with-go-zero/main.go
examples/with-http/main.go
examples/with-labstack-echo/main.go
examples/with-mux/main.go
examples/with-twirp/cmd/server/main.go

- Updates all example apps to also initialise the dashboard recipe
NA
NA
-   If no such branch exists, then create one …

chore: Add dashboard init to example apps

---

CHANGELOG.md
recipe/session/claimsWithJWT_test.go
recipe/session/config_test.go
recipe/session/main.go
recipe/session/recipe.go
recipe/session/sessmodels/models.go
recipe/session/utils.go
test/frontendIntegration/main.go

- The session recipe not always initialised the open id recipe if it isnt already initialised
- The session recipe config no longer accepts the `jwt` property
NOTE: The jwt property is removed from the user facing input but not the normalised version of it because the jwt is still present in the access token payload. In a future PR this will be cleaned up when the jwt is removed from the access token
WIP …

refactor: Automatically initialise OpenId recipe in session recipe (JWT Rework #3)

---

CHANGELOG.md
coreDriverInterfaceSupported.json
go.mod
go.sum
recipe/session/accessToken.go
recipe/session/assertClaims_test.go
recipe/session/claimsWithJWT_test.go
recipe/session/jwt.go
recipe/session/recipeImplementation.go
recipe/session/session.go
recipe/session/sessionFunctions.go
recipe/session/sessmodels/models.go
recipe/session/utils.go
supertokens/constants.go
supertokens/querier.go
supertokens/utils.go

- Updates CDI to 2.21
- Handled changes required for access token becoming a proper jwt
- Updates CHANGELOG to match all the changes made for jwt refactor so far
NOTE: Temporary changes were made for `checkDatabase` to be able to make requests to the core (TODOs are added for this). Temporarily commented some tests because they need changes, these will be made in future PRs
- 
-   [ ] Issue …

feat: Handle changes to access token becoming a JWT (JWT Rework #4)

---

CHANGELOG.md
recipe/dashboard/api/userdetails/userPut.go
recipe/emailpassword/authFlow_test.go
recipe/emailpassword/ep_userIdMapping_test.go
recipe/emailpassword/epmodels/recipeInterface.go
recipe/emailpassword/main.go
recipe/emailpassword/recipe.go
recipe/emailpassword/recipeImplementation.go
recipe/emailpassword/updateEmailPass_test.go
recipe/thirdpartyemailpassword/main.go
recipe/thirdpartyemailpassword/recipe.go
recipe/thirdpartyemailpassword/recipeimplementation/emailPasswordRecipeImplementation.go
recipe/thirdpartyemailpassword/recipeimplementation/main.go
recipe/thirdpartyemailpassword/tpepmodels/recipeInterface.go
supertokens/constants.go

Added optional password validation in `updateEmailOrPassword` function.
-   https://github.com/supertokens/supertokens-node/issues/549 (same implemented for golang)
-   To …

feat: optional password validation in updateEmailOrPassword

---

recipe/session/recipe.go
recipe/session/sessionFunctions.go
recipe/session/testingUtils.go
recipe/session/verifySession_test.go

- Adds a test to make sure that the SDK does not always call the core during session verification
- 
New tests added
- …

chore: Add test for verify session calling the core

---

CHANGELOG.md
recipe/session/main.go
recipe/session/recipeImplementation.go
recipe/session/sessionRequestFunctions.go
recipe/session/sessmodels/recipeInterface.go
supertokens/constants.go

- make loading access token from the request overrideable
- Made the access token string optional in the overrideable GetSession function
- Moved checking if the access token is nil into the overrideable GetSession function
- This is the golang equivalent of this PR in the node SDK: https://github.com/supertokens/supertokens-node/pull/562
- 
All existing tests should pass
NA
-   [x] Issue …

feat!: make loading access token from the request overrideable

---

CHANGELOG.md
recipe/session/session_test.go

- Add test to make sure JWTs without session claims do not result in get session throwing  an error when session required is false
-   
NA
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the …

[chore] Adds tests for GetSession

---

CHANGELOG.md
supertokens/constants.go
supertokens/logger.go

fix: issue with debug logging printing incorrect line number

---

CHANGELOG.md
recipe/session/accessToken.go
recipe/session/recipeImplementation.go
recipe/session/sessionFunctions.go
recipe/session/session_test.go
recipe/session/sessmodels/models.go
supertokens/constants.go
test/unittesting/testingutils.go

- Refactors the logic of fetching JWKs from the core to make sure that the SDK only calls it once every minute
- Fixes an issue where GetInfoFromAccessToken would not accept a pointer to `keyfunc.JWKS` which would result in jwt verification failing even after the keys are refreshed for an unknown KID
-  
Added tests to ensure that the fix works
NA
-   [x] Issue this PR against the latest non …

fix: Fix an issue where JWKs would be fetched multiple times a minute instead of once

---

recipe/session/recipeImplementation.go
recipe/session/session_test.go
recipe/session/sessmodels/models.go
recipe/session/testingUtils.go

- Refactors the JWKS fetching logic to:
- Not fetch JWKs on init
- Use a in memory cache for re-fetching instead of using keyfuncs background requests
- To stop fetching JWKs from cores after a valid response is received
- Adds additional tests to verify the JWKS behaviour (and adds comments explaining what the tests are meant to do)
- Adds code comments explaining the logic of the JWKS fetching setup
- 
Added new tests + all existing tests should pass
NA
-   In `supertokens/constants.go > …

refactor: Refactor JWKs fetching logic for session recipe

---

CHANGELOG.md
recipe/session/exposeAccessTokenToFrontendInCookieBasedAuth_test.go
recipe/session/jwt.go
recipe/session/session_test.go
supertokens/constants.go

- Refactors JWT parsing logic to assume latest access token version if the provided access token's header does not contain a version
- Adds a test to verify the above change
- Adds a test to make sure that only the access token is sent to the frontend if expose to frontend is set to true
- Adds a test to make sure JWKs locking works fine
- 
Adds tests
NA
-   [x] Issue this PR against the …

fix: Fix access token verification logic to use latest version if the JWT header has no version in it

---

CHANGELOG.md
recipe/emailverification/emaildelivery/smtpService/emailVerify.go
recipe/passwordless/emaildelivery/smtpService/passwordlessLogin.go
supertokens/constants.go

feat: email templates updated

---

recipe/session/session_test.go

Updates tests to run certain tests for specific CDI versions or above
- ...
NA
-   If no such branch exists, then create …

refactor: Update specific test to nor run on CDI version below 2.21

---

CHANGELOG.md

update/fix migration guide in changelog
- https://github.com/supertokens/supertokens-node/pull/603
- https://github.com/supertokens/supertokens-node/pull/601
N/A Docs only change
N/A Docs only change
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest …

docs: fix migration guide in changelog to be consistent with node

---

CHANGELOG.md
recipe/session/session_test.go
recipe/session/verifySession_test.go

- Adds a test to make sure session verification fails if the session was created with static signing keys but the current config is set to use dynamic signing keys
- Adds a test to make sure session verification does not fail if session required was false and no access token was passed
- 
Adds new tests
NA
-   To know …

chore: Add additional tests for session verification

---

CHANGELOG.md
recipe/session/sessionRequestFunctions.go
recipe/session/verifySession_test.go
supertokens/constants.go

- Adds additional tests for session verification
- Now properly ignoring missing anti-csrf tokens in optional session validation
- 
Adds new tests
NA
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater …

fix: properly ignoring anti-csrf in optional session validation

---

CHANGELOG.md
recipe/dashboard/api/userdetails/userPasswordPut.go
recipe/dashboard/api/userdetails/userPut.go
recipe/dashboard/userPasswordPut_test.go
recipe/dashboard/userPut_test.go
recipe/thirdpartyemailpassword/recipe.go
supertokens/constants.go

- Fixes an issue where updating a user's password from the dashboard would result in a pointer exception when using the thirdpartyemailpassword recipe (Also applied the fix when updating the user's email)
- Adds tests for userPasswordPut and userPut APIs to verify the fix
- https://github.com/supertokens/supertokens-golang/issues/311
Added new tests
NA
-   [x] Issue this PR against the …

fix: Fix issue with dashboard throwing an error when updating the user's password

---

recipe/dashboard/api/userdetails/userEmailVerifyPut.go
recipe/dashboard/api/userdetails/userEmailVerifyTokenPost.go
recipe/emailpassword/emailExistsAndVerificationCheck_test.go
recipe/emailpassword/ev_session_claim_test.go
recipe/emailverification/api/emailverify.go
recipe/emailverification/api/implementation.go
recipe/emailverification/evmodels/apiInterface.go
recipe/emailverification/evmodels/recipeInterface.go
recipe/emailverification/main.go
recipe/emailverification/recipe.go
recipe/emailverification/recipeimplementation.go
recipe/passwordless/api/implementation.go
recipe/passwordless/api_test.go
recipe/passwordless/recipe.go
recipe/session/accessTokenVersions_test.go
recipe/session/createNewSession_test.go
recipe/session/fetchAndSetClaim_test.go
recipe/session/removeClaim_test.go
recipe/session/setClaimValue_test.go
recipe/thirdparty/api/implementation.go
recipe/thirdpartyemailpassword/emailVerify_test.go
recipe/thirdpartypasswordless/recipeFunctions_test.go
test/auth-react-server/main.go

https://github.com/supertokens/supertokens-node/pull/606
-   In `supertokens/constants.go > version …

fix: multitenancy emailverification impl

---

.github/PULL_REQUEST_TEMPLATE.md
recipe/session/accessTokenVersions_test.go

Adds an additional test to make sure access token validation never fails because of claims that can be JSON null or skipped by the core
- 
Adds new test
NA
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is …

chore: Add test for access token validation

---

recipe/session/recipeImplementation.go
recipe/session/session_test.go
recipe/session/testingUtils.go

Made the test deterministic. There was a race condition in setting and checking the boolean returnedFromCache
-   In …

fix: jwks test

---

CHANGELOG.md
recipe/multitenancy/api/implementation.go
recipe/thirdpartyemailpassword/loginmethods_test.go
recipe/thirdpartypasswordless/config_test.go
recipe/thirdpartypasswordless/recipe.go
supertokens/constants.go

- Login methods must return empty array and not null
- Thirdparty should be initialized when no static providers are configured
-   [x] Changes to the version if …

fix: login methods api and tpless init

---

CHANGELOG.md
recipe/session/querier_test.go
supertokens/constants.go
supertokens/querier.go

refactor: Add handling for when Saas returns 429 because of rate limiting

---

CHANGELOG.md
recipe/session/accessTokenVersions_test.go
recipe/session/constants.go
recipe/session/main.go
recipe/session/recipeImplementation.go
recipe/session/sessionRequestFunctions.go

refactor: Ignore protected props in create new session

---

.circleci/config_continue.yml
.circleci/setupAndTestWithAuthReact.sh

chore: Update CICD config for installing node

---

CHANGELOG.md
recipe/session/config_test.go
supertokens/utils.go

fix: Fix same site parsing when using amazon public URLs

---

recipe/thirdparty/providers/twitter.go

chore: Add dev credentials handling to twitter

---

.circleci/config_continue.yml

fix: go version in circle ci

---

CHANGELOG.md
recipe/session/accessTokenVersions_test.go
recipe/thirdparty/provider_test.go
recipe/thirdparty/providers/config_utils.go
recipe/thirdparty/providers/github.go
recipe/thirdparty/providers/oauth2_impl.go
recipe/thirdparty/tpmodels/models.go
supertokens/constants.go

feat: Add ValidateAccessToken function to providers

---

CHANGELOG.md
recipe/session/cookieAndHeaders.go
recipe/session/verifySession_test.go
supertokens/constants.go

Adds tests
NA
-   [ ] add an icon on the user management dashboard.
-   To know which …

fix: Fix an issue where there would be duplicate headers in the value of Access-Control-Expose-Headers

---

.github/workflows/enforce-go-mod-tidy.yml
.github/workflows/pre-commit-hook-run.yml
.github/workflows/tests.yml
CHANGELOG.md
recipe/dashboard/api/analyticsPOST.go
recipe/dashboard/api/search/tagsGet.go
recipe/dashboard/api/signInPost.go
recipe/dashboard/api/signOutPost.go
recipe/dashboard/recipeimplementation.go
recipe/emailpassword/network_interceptor_test.go
recipe/emailpassword/recipeImplementation.go
recipe/emailverification/recipeimplementation.go
recipe/jwt/recipeimplementation.go
recipe/multitenancy/recipeimplementation.go
recipe/passwordless/recipeimplementation.go
recipe/session/accessTokenVersions_test.go
recipe/session/querier_test.go
recipe/session/recipeImplementation.go
recipe/session/sessionFunctions.go
recipe/thirdparty/recipeImplementation.go
recipe/usermetadata/recipeimplementation.go
recipe/userroles/recipeimplementation.go
supertokens/constants.go
supertokens/models.go
supertokens/querier.go
supertokens/supertokens.go
supertokens/userIdMapping.go
test/frontendIntegration/main.go

Added network interceptor hook. This can be used to capture/modify all the requests sent to the core.
- https://github.com/supertokens/supertokens-core/issues/865
Added unit test to test the flow. 
Further unit tests may need to be added to test the flow when the request object is modified.
-   [ ] update switch statement in …

feat: Added network interceptor hook

---

CHANGELOG.md
recipe/thirdparty/providers/github.go
supertokens/constants.go

Fixes issue with parsing github user id
-   https://github.com/supertokens/supertokens-golang/issues/387
-   [x] …

fix: github userid conversion

---

CHANGELOG.md
ingredients/emaildelivery/main.go
ingredients/emaildelivery/smtpmodels.go
supertokens/constants.go

Adds `TLSConfig` to `SMTPSettings` using which user can specify custom TLS config
Passes TLSConfig always to gomail so that it can be used when automatically using START TLS
-   https://github.com/supertokens/supertokens-golang/issues/392
Manually tested …

fix: smtp tls config

---

CHANGELOG.md
recipe/session/utils.go
supertokens/constants.go

SuperTokens-golang **Version 0.17.4**
This PR Adds a type `uint64` to the `accessTokenCookiesExpiryDurationMillis` local variable in `recipe/session/utils.go`. It also removes the redundant `uint64` type forcing needed because of the untyped variable.
While using GoReleaser to generate a release of my project using the supertokens-golang SDK it flagged an error building the binary for `linux_386` | `Linux i386`.
```bash
⨯ release failed after 52s  error=failed to build for linux_386: exit status 1: # github.com/supertokens/supertokens-golang/recipe/session
/root/go/pkg/mod/github.com/supertokens/supertokens-golang@v0.17.4/recipe/session/utils.go:242:46: cannot use 3153600000000 (untyped int constant) as int value in variable declaration (overflows)
```
#398 GoReleaser Fails on account of …

Added typing to avoid overflow warnings

---

CHANGELOG.md
recipe/emailpassword/authFlow_test.go
recipe/session/signout.go
recipe/thirdparty/signoutFeature_test.go

Fixing session required during signout
https://github.com/supertokens/supertokens-core/issues/554
-   [ ] update switch statement in `recipe/thirdparty/providers/config_utils.go` file, …

fix: session required in signout

---

CHANGELOG.md
recipe/session/apiImplementation.go
recipe/session/cookieAndHeaders.go
recipe/session/errors/errors.go
recipe/session/recipe.go
recipe/session/sessionRequestFunctions.go
recipe/session/session_test.go
recipe/session/sessmodels/models.go
recipe/session/utils.go
test/unittesting/testingutils.go

- Added `OlderCookieDomain` config option in the session recipe. This will allow users to clear cookies from older domain when the `CookieDomain` is changed.
- Fixed an issue where the access token wasn't cleared if refresh token API was called without a refresh token
https://github.com/supertokens/supertokens-node/issues/790
-   Along with the associated …

fix: duplicate session token issue when cookieDomain is changed

---

examples/with-labstack-echo/main.go

The issue is related to the usage of echo middleware in the `with-labstack-echo` example. Returning the `hf(c)` call will fix it.
**Why does it fix the issue?**
Because the error returned from the handler function is ignored when you don't return its result in the middleware chain. In the example, it ignores what `hf(c)` returns, instead returns `nil`. When we return as `return hf(c)`, the result of `hf(c)` will be respected.
https://discord.com/channels/603466164219281420/1227846962477535232
Added a test.
-   [ ] Changes to the …

fix: the with-labstack-echo example

---

recipe/session/session_test.go

fix: Add a test to check session cookies are cleared if refresh api is called with an expired access token

---

recipe/session/session_test.go

fix: increase wait time to allow access token to expire

---

CHANGELOG.md
recipe/emailpassword/querier_test.go
recipe/session/querier_test.go
supertokens/constants.go
supertokens/models.go
supertokens/querier.go
supertokens/supertokens.go
supertokens/utils.go

Related to https://github.com/supertokens/supertokens-python/pull/508
-   [ ] add an icon on the user management dashboard.
-   To know which one it is, run find the …

Querier caching

---

CHANGELOG.md
recipe/session/utils.go
supertokens/constants.go

We decided to update the cookie expiry to 1 year because - 
1. Some browsers cap the max expiry to 400 days. See [this](https://developer.chrome.com/blog/cookie-max-age-expires#:~:text=With%20this%20change%2C%20Chrome%20caps,set%20to%20400%20days%20instead) for info.
2. Our docs mention that access token cookie expiry is 1 year.
-   [ ] `coreDriverInterfaceSupported.json` file has …

fix: update access token cookie expiry to 1 year

---

CHANGELOG.md
recipe/emailpassword/authMode_test.go
recipe/session/sessionRequestFunctions.go
supertokens/constants.go

test: move the session object and claims to the BE sdk server
Updated existing tests
N/A
-   [ ] add an icon on the user management dashboard.
-   [ ] Issue this PR against the latest non …

test: move the session object and claims to the BE sdk server

---

CHANGELOG.md
recipe/emailverification/emailverificationClaim.go
recipe/emailverification/emailverificationClaim_test.go
supertokens/constants.go

This PR removes the default `maxAgeInSeconds` value (previously 300 seconds) in EmailVerification Claim. If the claim value is true and `maxAgeInSeconds` is not provided, it will not be refetched.
-   [ ] …

feat!: remove default maxAgeInSeconds in emailverification claim

---

CHANGELOG.md
recipe/session/jwksMemory_test.go
recipe/session/recipeImplementation.go
supertokens/constants.go

Fixes memory leak in JWKS refresh.
Added unit test
-   [ ] add an icon on the user …

fix: memory leak in jwks

---

recipe/emailpassword/api/utils.go
recipe/emailpassword/authFlow_test.go

This improves the form field validation to make sure that optional fields are actually optional
Copy of https://github.com/supertokens/supertokens-node/pull/919 from the node repo.
emailpassword tests should pass
-   [ ] If new thirdparty …

Improve form field validation to make optional truly optional

---

CHANGELOG.md
recipe/dashboard/api/usersGet.go
supertokens/constants.go

- Fixes dashboard crashing on refresh (due to user GET API making the SDK crash)
- Bumps version to 0.25.0
Example go app with dashboard recipe should not crash on refreshes.
-   [ ] update switch …

fix: concurrent map writes error and version bump

---

CHANGELOG.md

This PR updates the changelog to add migration details for using `TypeFormField` value.
-   [ ] update switch statement in `recipe/thirdparty/providers/config_utils.go` file, `createProvider` …

fix: Update changelog with migration guide for form field value consumption

---

CHANGELOG.md
recipe/dashboard/api/implementation.go
recipe/dashboard/dashboardGet_test.go
supertokens/constants.go

This PR adds support for normalizing connection URI before returning them in dashboard GET.
Copy of https://github.com/supertokens/supertokens-node/pull/760 from the node SDK.
- https://github.com/supertokens/supertokens-node/pull/760
- dashboardGet_test.go should pass
-   [x] Had installed …

feat: normalise dashboard connection url
